name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Client Side
        run: |
          npm i
          cd client
          npm i
          npm run build
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_API_VERSION: ${{ vars.VITE_API_VERSION }}
          VITE_LOGO_MINI: $${{ vars.VITE_LOGO_MINI }}
          VITE_LOGO_BIG_BNW: ${{ vars.VITE_LOGO_BIG_BNW }}
          VITE_LOGO_BIG: ${{ vars.VITE_LOGO_BIG }}