name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Client Side
        run: |
          npm i
          cd client
          npm i
          npm run build
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
        env:
          NODE_ENV: "product"
          VITE_API_URL: "http://134.209.97.214:8000"
          VITE_API_VERSION: "v1"
          VITE_LOGO_MINI: "global_mini.svg"
          VITE_LOGO_BIG_BNW: "global_big_bnw.svg"
          VITE_LOGO_BIG: "global_big.svg"